export const NavigationActions = {
    SHOW_FLOWERS: 'SHOW_FLOWERS',
    SHOW_LATEST_SIGHTINGS: 'SHOW_LATEST_SIGHTINGS',
    SHOW_FAVORITES: 'SHOW_FAVORITES',
    SHOW_LOGIN_MODAL: 'SHOW_LOGIN_MODAL',
    SHOW_SIGNUP_MODAL: 'SHOW_SIGNUP_MODAL'
}