const UserAuthActionTypes = {
    USER_LOGIN_SUCCESS : 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
    USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    USER_SIGNUP_SUCCESS : 'USER_SIGNUP_SUCCESS',
    USER_SIGNUP_FAILURE: 'USER_SIGNUP_FAILURE',
    USER_SIGNUP_REQUEST: 'USER_SIGNUP_REQUEST',
    GET_USER_PROFILE: 'GET_USER_PROFILE',
    SHOW_USER_SECTION: 'SHOW_USER_SECTION',
    SHOW_USER_PROFILE: 'SHOW_USER_PROFILE'
}

export default UserAuthActionTypes
